export enum requestTargetN3 {
    N3Provider = 'neoline.target_provider_n3',
    N3Networks = 'neoline.target_networks_n3',
    N3Account = 'neoline.target_account_n3',
    N3AccountPublicKey = 'neoline.target_public_key_n3',
    N3Storage = 'neoline.target_storage_n3',
    N3InvokeRead = 'neoline.target_invoke_read_n3',
    N3InvokeReadMulti = 'neoline.target_invoke_read_multi_n3',
    N3VerifyMessage = 'neoline.target_verify_message_n3',
    N3Transaction = 'neoline.target_transaction_n3',
    N3Block = 'neoline.target_block_n3',
    N3ApplicationLog = 'neoline.target_application_log_n3',
    N3Invoke = 'neoline.target_invoke_n3',
    N3InvokeMulti = 'neoline.target_invoke_multi_n3',
    N3SignMessage = 'neoline.target_sign_message_n3',
    N3Deploy = 'neoline.target_deploy_n3',
    N3Send = 'neoline.target_send_n3',
    N3Connect = 'neoline.target_connect_n3',
    N3AuthState = 'neoline.target_auth_state_n3',
    N3Login = 'neoline.target_login_n3',
    N3Balance = 'neoline.target_balance_n3',
    N3InvokeMultiple = 'neoline.target_invoke_multiple_n3',
}
