export const INIT_ACCOUNT = 'INIT_ACCOUNT';
export const RESET_ACCOUNT = 'RESET_ACCOUNT';
export const UPDATE_WALLET = 'UPDATE_WALLET';

export const ADD_NEO2_WALLETS = 'ADD_NEO2_WALLETS';
export const ADD_NEO3_WALLETS = 'ADD_NEO3_WALLETS';
export const ADD_NEOX_WALLET = 'ADD_NEOX_WALLET';

export const REMOVE_NEO2_WALLET = 'REMOVE_NEO2_WALLET';
export const REMOVE_NEO3_WALLET = 'REMOVE_NEO3_WALLET';
export const REMOVE_NEOX_WALLET = 'REMOVE_NEOX_WALLET';

export const UPDATE_NEO2_WALLET_NAME = 'UPDATE_NEO2_WALLET_NAME';
export const UPDATE_NEO3_WALLET_NAME = 'UPDATE_NEO3_WALLET_NAME';
export const UPDATE_NEOX_WALLET_NAME = 'UPDATE_NEOX_WALLET_NAME';

export const UPDATE_NEO2_WALLET_BACKUP_STATUS = 'UPDATE_NEO2_WALLET_BACKUP_STATUS';
export const UPDATE_NEO3_WALLET_BACKUP_STATUS = 'UPDATE_NEO3_WALLET_BACKUP_STATUS';
export const UPDATE_NEOX_WALLET_BACKUP_STATUS = 'UPDATE_NEOX_WALLET_BACKUP_STATUS';


export const UPDATE_NEO3_WALLETS_ADDRESS = 'UPDATE_NEO3_WALLETS_ADDRESS';
export const UPDATE_ALL_WALLETS = 'UPDATE_ALL_WALLETS';

export const ADD_NEO3_NETWORK = 'ADD_NEO3_NETWORK';
export const ADD_NEOX_NETWORK = 'ADD_NEOX_NETWORK';

export const UPDATE_NEO2_NETWORKS = 'UPDATE_NEO2_NETWORKS';
export const UPDATE_NEO3_NETWORKS = 'UPDATE_NEO3_NETWORKS';
export const UPDATE_NEOX_NETWORKS = 'UPDATE_NEOX_NETWORKS';

export const UPDATE_NEO2_NETWORK_INDEX = 'UPDATE_NEO2_NETWORK_INDEX';
export const UPDATE_NEO3_NETWORK_INDEX = 'UPDATE_NEO3_NETWORK_INDEX';
export const UPDATE_NEOX_NETWORK_INDEX = 'UPDATE_NEOX_NETWORK_INDEX';
